stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $DOCKER_TAG_ALPINE
  DOCKERHUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKER_HUB_PASSWORD

before_script:
  - export DOCKER_HOST=tcp://docker:2375/

image: docker:24.0.5
services:
  - docker:24.0.5-dind
before_script:
  - docker info

build_debian:
  stage: build
  only: 
    - master
  script:
    - docker info
    - echo $DOCKERHUB_USERNAME
    - docker build -t $DOCKER_IMAGE_NAME -f dockerfile.template .
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker push $DOCKER_IMAGE_NAME

# deploy_alpine:
#   stage: deploy
#   only:
#     - master  # Deploy only when changes are pushed to master branch
#   script:
#     - docker info
#     - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
#     - docker pull $DOCKER_IMAGE_NAME:latest
#     - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:staging
#     - docker push $DOCKER_IMAGE_NAME:staging
