# Use the official PHP 8.2 Apache base image
FROM php:8.2-apache

# Remove default apache conf
RUN rm /etc/apache2/sites-available/000-default.conf

# Install Dependencies
RUN apt-get update && \
    apt-get install -y libicu-dev unzip && \
    docker-php-ext-install intl && \
    docker-php-ext-install mysqli pdo pdo_mysql && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer